apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  version: "4.4.0"
  externalConnectivity:
    type: LoadBalancer
  adminCredentials: ops-manager-admin-secret
  configuration:
    mms.fromEmailAddr: "admin@example.com"
    mms.replyToEmailAddr: "admin@example.com"
    mms.adminEmailAddr: "admin@example.com"
    mms.emailDaoClass: "com.xgen.svc.core.dao.email.JavaMailEmailDAO"
    mms.emailDaoConfig.server: "smtp.example.com"
  applicationDatabase:
    members: 3
    version: "4.2.6"