apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: hr-mongodb
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.0"
  security:
    authentication:
      enabled: true 
      modes: ["SCRAM"]
  opsManager:
    configMapRef:
      name: ops-manager-connection
  credentials: mongodb-admin-secret
